"""Populate the database with demo accounts and ~70 days of historical data.

Historical predictions are generated by calling the REAL predictor
(ml/predictor.py) chronologically, exactly as the live app would — so the
prediction-accuracy numbers you see in analytics are genuine, not faked.

Run:  python seed.py [--reset]
"""
import argparse
import random
from datetime import date, timedelta
from pathlib import Path

from app import create_app
from db import get_db, get_or_create_meal
from werkzeug.security import generate_password_hash
from ml.predictor import predict_attendance
from ml.preparation import recommend_servings

random.seed(42)

MEAL_TYPES = ["breakfast", "lunch", "dinner"]
BASE_ATTENDANCE = {"breakfast": 230, "lunch": 430, "dinner": 370}
REASONS = ["portion_too_large", "disliked_taste", "too_spicy", "food_quality", "food_cold", "not_hungry", "other"]
REASON_WEIGHTS = [0.32, 0.14, 0.10, 0.12, 0.10, 0.14, 0.08]

DEMO_STAFF = [
    {"name": "Ramesh Iyer", "email": "staff1@mess.edu", "password": "staff123"},
    {"name": "Anita Verma", "email": "staff2@mess.edu", "password": "staff123"},
]

# A realistic-sized student pool. Feedback rows require a real user account (that's an
# actual database constraint, not a display choice), so a tiny pool of demo students is
# why coverage numbers looked implausibly small earlier — 120 gives coverage percentages
# in a believable range (roughly 5-20% of a few hundred diners) without needing to fake
# thousands of individual accounts for a student project.
N_DEMO_STUDENTS = 120
DEMO_STUDENT_NAMES = [
    "Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai", "Reyansh", "Ayaan", "Krishna", "Ishaan",
    "Ananya", "Diya", "Saanvi", "Aadhya", "Kavya", "Myra", "Anika", "Pari", "Riya", "Ira",
]

def _build_demo_students():
    students = []
    for i in range(1, N_DEMO_STUDENTS + 1):
        first = DEMO_STUDENT_NAMES[(i - 1) % len(DEMO_STUDENT_NAMES)]
        students.append({
            "name": f"{first} {'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[(i - 1) // len(DEMO_STUDENT_NAMES) % 26]}.",
            "email": f"student{i}@vit.edu",
            "password": "student123",
        })
    return students

DEMO_STUDENTS = _build_demo_students()

HISTORY_DAYS = 70


def true_demand(base, weekday, day_type):
    mult = 1.0
    if day_type == "weekend":
        mult *= 0.82
    elif day_type == "holiday":
        mult *= 0.55
    elif day_type == "festival":
        mult *= 0.65
    # mild day-of-week ripple even within weekdays
    mult *= 1.0 + [0.02, 0.00, -0.01, 0.01, 0.03, 0, 0][weekday]
    noise = random.gauss(0, 0.05)
    return max(20, round(base * mult * (1 + noise)))


def seed_users(db):
    ids = {"staff": [], "student": []}
    for u in DEMO_STAFF:
        cur = db.execute(
            "INSERT OR IGNORE INTO users (name, email, password_hash, role) VALUES (?, ?, ?, 'staff')",
            (u["name"], u["email"], generate_password_hash(u["password"], method="pbkdf2:sha256:260000")),
        )
        row = db.execute("SELECT id FROM users WHERE email = ?", (u["email"],)).fetchone()
        ids["staff"].append(row["id"])
    for u in DEMO_STUDENTS:
        db.execute(
            "INSERT OR IGNORE INTO users (name, email, password_hash, role) VALUES (?, ?, ?, 'student')",
            (u["name"], u["email"], generate_password_hash(u["password"], method="pbkdf2:sha256:260000")),
        )
        row = db.execute("SELECT id FROM users WHERE email = ?", (u["email"],)).fetchone()
        ids["student"].append(row["id"])
    db.commit()
    return ids


def seed_calendar(db, start, end):
    events = []
    d = start
    while d <= end:
        if d.weekday() == 4 and d.day <= 7:  # first Friday of each month -> pretend holiday
            events.append((d.isoformat(), "Institute Holiday", "holiday"))
        d += timedelta(days=1)
    # one clearly marked festival roughly a month in
    festival_date = start + timedelta(days=30)
    events.append((festival_date.isoformat(), "Regional Festival", "festival"))
    for date_str, name, day_type in events:
        db.execute(
            "INSERT OR IGNORE INTO calendar_events (date, name, day_type) VALUES (?, ?, ?)",
            (date_str, name, day_type),
        )
    db.commit()


def seed_history(db, staff_ids, student_ids, start, end):
    from calendar_context import context_for

    d = start
    while d <= end:
        date_str = d.isoformat()
        for meal_type in MEAL_TYPES:
            meal = get_or_create_meal(db, date_str, meal_type)
            ctx = context_for(db, date_str)

            # 1. Predict using the real predictor, based only on history strictly before this date.
            result = predict_attendance(db, date_str, meal_type)
            db.execute(
                """INSERT OR IGNORE INTO predictions
                   (meal_id, predicted_diners, method, confidence_note, historical_samples)
                   VALUES (?, ?, ?, ?, ?)""",
                (meal["id"], result["predicted_diners"], result["method"],
                 result["confidence_note"], result["historical_samples"]),
            )

            # 2. The "true" attendance that actually happened (independent of the prediction).
            actual_attendance = true_demand(BASE_ATTENDANCE[meal_type], d.weekday(), ctx["day_type"])
            staff_id = random.choice(staff_ids)
            db.execute(
                """INSERT OR IGNORE INTO attendance (meal_id, official_count, source, recorded_by)
                   VALUES (?, ?, 'college_system', ?)""",
                (meal["id"], actual_attendance, staff_id),
            )

            # 3. Preparation: staff accepts the recommended servings (with small real-world variance).
            # Historically, attendance for a meal is only confirmed once the meal happens — so at
            # planning time the ML prediction was the only basis available, same as production.
            calc = recommend_servings(result["predicted_diners"])
            confirmed = calc["recommended_servings"] + random.randint(-5, 5)
            actual_prepared = max(confirmed - random.randint(0, 4), 0)
            actual_served = min(actual_prepared, actual_attendance + random.randint(-3, 3))
            actual_served = max(actual_served, 0)
            db.execute(
                """INSERT OR IGNORE INTO preparation
                   (meal_id, basis, base_count, safety_buffer, recommended_servings,
                    confirmed_servings, actual_prepared, actual_served, confirmed_by)
                   VALUES (?, 'prediction', ?, ?, ?, ?, ?, ?, ?)""",
                (meal["id"], calc["predicted_diners"], calc["safety_buffer"], calc["recommended_servings"],
                 confirmed, actual_prepared, actual_served, staff_id),
            )

            # 4. Plate waste: each served student wastes a small random amount; staff weighs the total.
            per_head_grams = max(0, random.gauss(70, 25))
            weight_kg = round((actual_served * per_head_grams) / 1000, 1)
            db.execute(
                "INSERT OR IGNORE INTO plate_waste (meal_id, weight_kg, entered_by) VALUES (?, ?, ?)",
                (meal["id"], weight_kg, staff_id),
            )

            # 5. Feedback: a realistic minority of students engage with the app for this meal.
            # Ratings and waste reasons are drawn from an overlapping "engaged" pool (rather than
            # two independent random draws) so the numbers relate to each other the way real
            # feedback data would — and reason-reporting scales with how much was actually wasted.
            engaged_frac = random.uniform(0.15, 0.45)
            engaged_n = max(3, round(len(student_ids) * engaged_frac))
            engaged = random.sample(student_ids, k=min(engaged_n, len(student_ids)))

            rating_frac = random.uniform(0.55, 0.9)
            rating_responders = random.sample(engaged, k=round(len(engaged) * rating_frac))
            waste_ratio = min(1.0, per_head_grams / 130)  # heavier per-head waste -> ratings skew lower
            for sid in rating_responders:
                weights = [0.05 + 0.25 * waste_ratio, 0.20, 0.40 - 0.10 * waste_ratio, 0.35 - 0.15 * waste_ratio]
                weights = [max(0.02, w) for w in weights]
                rating = random.choices([2, 3, 4, 5], weights=weights, k=1)[0]
                db.execute(
                    "INSERT OR IGNORE INTO meal_ratings (meal_id, student_id, rating) VALUES (?, ?, ?)",
                    (meal["id"], sid, rating),
                )

            reason_frac = random.uniform(0.20, 0.55) * (0.4 + 0.6 * waste_ratio)
            reason_n = round(len(engaged) * reason_frac)
            reason_responders = random.sample(engaged, k=min(reason_n, len(engaged)))
            for sid in reason_responders:
                reason = random.choices(REASONS, weights=REASON_WEIGHTS, k=1)[0]
                db.execute(
                    "INSERT OR IGNORE INTO waste_reasons (meal_id, student_id, reason) VALUES (?, ?, ?)",
                    (meal["id"], sid, reason),
                )

            opt_out_students = random.sample(student_ids, k=random.randint(0, max(1, round(len(student_ids) * 0.06))))
            for sid in opt_out_students:
                db.execute(
                    "INSERT OR IGNORE INTO opt_outs (meal_id, student_id) VALUES (?, ?)",
                    (meal["id"], sid),
                )

        db.commit()
        d += timedelta(days=1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--reset", action="store_true", help="delete the existing database file first")
    args = parser.parse_args()

    db_path = Path(__file__).parent / "instance" / "sfms.db"
    if args.reset and db_path.exists():
        db_path.unlink()

    app = create_app()
    with app.app_context():
        db = get_db()
        ids = seed_users(db)

        end = date.today() - timedelta(days=1)  # leave "today" unseeded for live demo
        start = end - timedelta(days=HISTORY_DAYS - 1)
        seed_calendar(db, start, end)
        seed_history(db, ids["staff"], ids["student"], start, end)

    print(f"Seeded {HISTORY_DAYS} days of history ({start} to {end}).")
    print("Demo staff login:  staff1@mess.edu / staff123")
    print(f"Demo student login: student1@vit.edu / student123  (also student2..student{N_DEMO_STUDENTS})")


if __name__ == "__main__":
    main()
